name: PHP-CS-Fixer

on:
  push:

jobs:
  php_cs_fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Prepare the environment
        run: cp .env.test .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHP CS Fixer (dry run)
        run: composer fix:dry
