name: PHPStan

on:
  push:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Prepare the environment
        run: cp .env.test .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Warm up test container
        run: php bin/console cache:warmup --env=test

      - name: Wait for the test container to be ready
        run: sleep 2

      - name: Run PHPStan
        run: composer stan
